module.exports = {
  OK: 200,
  SUCCESSFULLY_UPDATED_PRODUCT: 200,
  SUCCESSFULLY_CREATED_PRODUCT: 201,
  SUCCESSFULLY_CREATED_SALE: 201,
  SUCCESSFULLY_DELETED_SALE: 204,
  SUCCESSFULLY_EDITED_SALE: 200,
  SUCCESSFULLY_DELETED_PRODUCT: 204,
  'any.required': 400,
  'string.empty': 400,
  UNSUCCESSFULLY_CREATED_PRODUCT: 401,
  PRODUCT_NOT_FOUND: 404,
  SALE_NOT_FOUND: 404,
  'string.min': 422,
  'number.min': 422,

};
